/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CovidStatistics {
        "Parameter": string;
    }
}
declare global {
    interface HTMLCovidStatisticsElement extends Components.CovidStatistics, HTMLStencilElement {
    }
    var HTMLCovidStatisticsElement: {
        prototype: HTMLCovidStatisticsElement;
        new (): HTMLCovidStatisticsElement;
    };
    interface HTMLElementTagNameMap {
        "covid-statistics": HTMLCovidStatisticsElement;
    }
}
declare namespace LocalJSX {
    interface CovidStatistics {
        "Parameter"?: string;
    }
    interface IntrinsicElements {
        "covid-statistics": CovidStatistics;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "covid-statistics": LocalJSX.CovidStatistics & JSXBase.HTMLAttributes<HTMLCovidStatisticsElement>;
        }
    }
}
